package com.cloudstorage.backend.entity;

public enum ActivityType {
    WORKSPACE_CREATED,
    WORKSPACE_UPDATED,
    WORKSPACE_DELETED,
    MEMBER_INVITED,
    MEMBER_JOINED,
    MEMBER_REMOVED,
    ROLE_CHANGED,
    OWNERSHIP_TRANSFERRED,
    FILE_SHARED,
    FILE_PERMISSION_GRANTED,
    FILE_PERMISSION_REVOKED,
    WORKSPACE_QUOTA_UPDATED
}
